// The debug hook — `window.__stores`, how e2e suites (and a curious developer) reach the app's
// singletons. Opt-in: App.svelte installs it only when safeStorage holds `debugStores`.
//
// 34 R4 (A2): ONE ROW PER HOOK, its name and its loader on the same line. This replaced App.svelte's
// three POSITIONAL tails (a Promise.all import list, a destructured parameter list and the
// `window.__stores` object literal) that every lane edited and every merge could silently shift —
// a missing binding bound each later module to its neighbour's name with no error anywhere. A row
// cannot shift: add `['name', () => import('./x')]` anywhere in the list (order does not matter;
// names must be unique — the debug-hooks suite checks). `'*'` SPREADS a module's exports straight
// onto `__stores` (the three stores, as before); every named row is applied after them, so a named
// hook wins a clash exactly as it did in the old object literal.
//
// The loaders stay DYNAMIC on purpose: this table must never pull ~200 modules into the boot graph
// of a session that did not ask for the hook. Code that already holds an object can publish it with
// `registerDebugHook(name, obj)` (before or after the install) instead of adding a row.

/** @type {[string, () => Promise<any>][]} */
export const DEBUG_HOOKS = [
	['*', () => import('../stores/sceneStore')],
	['*', () => import('../stores/appStore')],
	['*', () => import('../stores/flowStore')],
	// 34 R2: the game kit (kit, kitDebug, kitAuthorityId)
	['kit', () => import('./kit/runtime.js')],
	// 34 R2 (kit-entities): entities drawn / world / api (kitEntitiesDebug, kitEntitiesApi, entityOfObject)
	['kitEntities', () => import('./kit/entityApp.js')],
	// 34 R3 (D1/D2): behaviours (runtime, behaviourStatus, behavioursDebug)
	['behaviours', () => import('./behaviours/app.js')],
	['meshEdit', () => import('./meshEdit')],
	['perf', () => import('./perf/recorder')],
	['perfDetailed', () => import('./perf/detailed')],
	['perfBeacon', () => import('./perf/beacon')],
	['staleModules', () => import('./staleModules')],
	['perfMoment', () => import('./perf/moment')],
	['profilerView', () => import('./perf/profilerView')],
	['profilerModel', () => import('./perf/profilerModel.js')],
	['vrRecIndicator', () => import('./vrRecIndicator')],
	// 36 U3b/I5: the tour engine (tours, activeTour, toursDebug) + the built-in tours
	['tours', () => import('./tours/index.js')],
	['toursBuiltin', () => import('./tours/builtin.js')],
	['tourVR', () => import('./tours/vrPanel.js')],
	['perfLiveSource', () => import('./perf/liveSource')],
	['perfLiveSink', () => import('./perf/liveSink')],
	['perfLiveWire', () => import('./perf/liveWire')],
	['vrControls', () => import('./vrControls')],
	['autosave', () => import('./autosave')],
	['voiceChat', () => import('./voiceChat')],
	['audioEngine', () => import('./audioEngine')],
	['musicClock', () => import('./musicClock')],
	['audioDevices', () => import('./audioDevices')],
	['audioPatch', () => import('./audioPatch')],
	['vrPatch', () => import('./vrPatch')],
	['musicToolbox', () => import('./musicToolbox')],
	['micCapture', () => import('./micCapture')],
	['annotationsHandler', () => import('./annotationsHandler')],
	['flowRuntime', () => import('./flowRuntime')],
	['history', () => import('./history')],
	['materialsHandler', () => import('./materialsHandler')],
	['objectActions', () => import('./objectActions')],
	['commandsHandler', () => import('./commandsHandler.svelte')],
	['moduleSDK', () => import('./moduleSDK')],
	['moduleLifecycle', () => import('./sdk/lifecycleEnv.js')],
	['drawMode', () => import('./drawMode')],
	['pathCapture', () => import('./pathCapture')],
	['lockControl', () => import('./lockControl')],
	['prefabs', () => import('./prefabs')],
	['physics', () => import('./physics')],
	['joints', () => import('./joints')],
	['possess', () => import('./possess')],
	['handModels', () => import('./handModels')],
	['terrainSculpt', () => import('./terrainSculpt')],
	['userModules', () => import('./userModules')],
	['environment', () => import('./environment')],
	['sceneMusic', () => import('./sceneMusic')],
	['animatedImports', () => import('./animatedImports')],
	['fileHandler', () => import('./fileHandler.svelte')],
	['fileWindows', () => import('./fileWindows')],
	['sceneBounds', () => import('./sceneBounds')],
	['cameraClip', () => import('./cameraClip')],
	['ping', () => import('./ping')],
	['sessions', () => import('./sessions')],
	['geometryEdit', () => import('./geometryEdit')],
	['lightParams', () => import('./lightParams')],
	['shadowDefaults', () => import('./shadowDefaults')],
	['palette', () => import('./palette')],
	['viewModeCtl', () => import('./viewMode')],
	['inputRuntime', () => import('./inputRuntime')],
	['shortcutsRegistry', () => import('./shortcuts')],
	['themes', () => import('./themes')],
	['vrRadialMenu', () => import('./vrRadialMenu')],
	['vrPalette', () => import('./vrPalette')],
	['vrWindowPoses', () => import('./vrWindowPoses')],
	['vrKeyboard', () => import('./vrKeyboard')],
	['faceEdit', () => import('./faceEdit')],
	['meshToolParams', () => import('./meshToolParams')],
	['avatarModel', () => import('./avatarModel')],
	['explorer', () => import('./explorer')],
	['bottomDock', () => import('./bottomDock')],
	['explorerDrop', () => import('./explorerDrop')],
	['assetShare', () => import('./assetShare')],
	['soundRuntime', () => import('./soundRuntime')],
	['dungeonPlay', () => import('./dungeonPlay')],
	['modelLoader', () => import('./modelLoader')],
	['sceneAssets', () => import('./sceneAssets')],
	['THREE', () => import('three')],
	['GLTFExporterModule', () => import('three/addons/exporters/GLTFExporter.js')],
	['snapping', () => import('./snapping')],
	['flowSockets', () => import('./flowSockets')],
	['networkQuality', () => import('./networkQuality')],
	['packs', () => import('./packs')],
	['customNodes', () => import('./customNodes')],
	['nodesHandler', () => import('./nodesHandler')],
	['nodeCatalog', () => import('./nodeCatalog')],
	['objectMenu', () => import('./objectMenu')],
	['animationPreview', () => import('./animationPreview')],
	['aiProviders', () => import('./ai/providers')],
	['aiTools', () => import('./ai/tools')],
	['aiAssistant', () => import('./ai/assistant')],
	['meshProviders', () => import('./ai/meshProviders')],
	['meshJobs', () => import('./ai/meshJobs')],
	['flowGraphsCtl', () => import('./flowGraphs')],
	['objectFlow', () => import('./objectFlow')],
	['peerServer', () => import('./peerServer')],
	['cloudHooks', () => import('./cloudHooks')],
	['cloudPlugin', () => import('./cloudPlugin')],
	['connectionState', () => import('./connectionState')],
	['peerApproval', () => import('./peerApproval')],
	['particleRuntime', () => import('./particleRuntime')],
	['particleActions', () => import('./particleActions')],
	['particlePresets', () => import('./particlePresets')],
	['version', () => import('./version')],
	['whatsNew', () => import('./whatsNew')],
	['confirmDialog', () => import('./confirmDialog')],
	['scenePhysics', () => import('./scenePhysics')],
	['playInteract', () => import('./playInteract')],
	['moveSmoothing', () => import('./moveSmoothing')],
	['knock', () => import('./knock')],
	['playSettings', () => import('./playSettings')],
	['colliderSpec', () => import('./colliderSpec')],
	['colliderHelpers', () => import('./colliderHelpers')],
	['colliderEdit', () => import('./colliderEdit')],
	['editSession', () => import('./editSession')],
	['trackpadNav', () => import('./trackpadNav')],
	['vrSleeve', () => import('./vrSleeve')],
	['gridSettings', () => import('./gridSettings')],
	['viewPrefs', () => import('./viewPrefs')],
	['cameraBookmarks', () => import('./cameraBookmarks')],
	['cameraObjects', () => import('./cameraObjects')],
	['cameraHelpers', () => import('./cameraHelpers')],
	['onionSkin', () => import('./onionSkin')],
	['cameraPreview', () => import('./cameraPreview')],
	['addObjects', () => import('./addObjects')],
	['cameraPip', () => import('./cameraPip')],
	['inputDevice', () => import('./inputDevice')],
	['sceneTemplates', () => import('./sceneTemplates')],
	['bvhPicking', () => import('./bvhPicking')],
	['multiTransform', () => import('./multiTransform')],
	['objectOrigin', () => import('./objectOrigin')],
	['moduleGallery', () => import('./moduleGallery')],
	['uvEditor', () => import('./uvEditor')],
	['uvUnwrap', () => import('./uvUnwrap')],
	['meshTopology', () => import('./meshTopology')],
	['meshBudget', () => import('./meshBudget')],
	['proportional', () => import('./proportional')],
	['proportionalRing', () => import('./proportionalRing')],
	['scenePick', () => import('./scenePick')],
	['snapEngine', () => import('./snapEngine')],
	['meshPivot', () => import('./meshPivot')],
	['selectionPrefs', () => import('./selectionPrefs')],
	['editOverlays', () => import('./editOverlays')],
	['objectPermissions', () => import('./objectPermissions')],
	['scenePost', () => import('./scenePost')],
	['postEffects', () => import('./postEffects')],
	['viewportOverrides', () => import('./viewportOverrides')],
	['postprocessing', () => import('postprocessing')],
	['shaderBackends', () => import('./shaderBackends')],
	['shaderGraph', () => import('./shaderGraph')],
	['shaderSync', () => import('./shaderSync')],
	['shaderTextures', () => import('./shaderTextures')],
	['shaderCatalog', () => import('./shaderCatalog')],
	['units', () => import('./units')],
	['postBackends', () => import('./postBackends')],
	['workspace', () => import('./workspace')],
	['editResume', () => import('./editResume')],
	['moduleRequirements', () => import('./moduleRequirements')],
	['hudDocs', () => import('./hudDocs')],
	['hudSync', () => import('./hudSync')],
	['idb', () => import('./idb')],
	['hudKinds', () => import('./hudKinds')],
	['hudImages', () => import('./hudImages')],
	['gameState', () => import('./gameState')],
	['gameSync', () => import('./gameSync')],
	['hudActions', () => import('./hudActions')],
	['moduleNodeIO', () => import('./moduleNodeIO')],
	['moduleToolboxes', () => import('./moduleToolboxes')],
	['splineTube', () => import('./splineTube')],
	['splineTool', () => import('./splineTool')],
	['splineEdit', () => import('./splineEdit')],
	['terrainCarve', () => import('./terrainCarve')],
	['flattenActions', () => import('./flattenActions')],
	['hudViewportDrag', () => import('./hudViewportDrag')],
	['gamepadPrefs', () => import('./gamepadPrefs')],
	['charController', () => import('./charController')],
	['hudRichText', () => import('./hudRichText')],
	['moduleHudKinds', () => import('./moduleHudKinds')],
	['hudMinimap', () => import('./hudMinimap')],
	['hudArrange', () => import('./hudArrange')],
	['gamePresence', () => import('./gamePresence')],
	['levels', () => import('./levels')],
	['peerVars', () => import('./peerVars')],
	['projectManifest', () => import('./projectManifest')],
	['projectFile', () => import('./projectFile')],
	['transientObjects', () => import('./transientObjects')],
	['spawner', () => import('./spawner')],
	['triggerSync', () => import('./triggerSync')],
	['saveName', () => import('./saveName')],
	['sceneIdentity', () => import('./sceneIdentity')],
	['importDuplicates', () => import('./importDuplicates')],
	['peerScenes', () => import('./peerScenes')],
	['sharedLibrary', () => import('./sharedLibrary')],
	['transferLedger', () => import('./transferLedger')],
	['explorerView', () => import('./explorerView')],
	['filePreview', () => import('./filePreview')],
	['saveAs', () => import('./saveAs')],
	['windowTabs', () => import('./windowTabs')],
	['colocation', () => import('./colocation')],
	['colocationCalibrate', () => import('./colocationCalibrate')],
	['colocationPresence', () => import('./colocationPresence')],
	['xrAnchors', () => import('./xrAnchors')],
	['colocationAnchors', () => import('./colocationAnchors')],
	['colocationNudge', () => import('./colocationNudge')],
	['mountedVolumes', () => import('./mountedVolumes')],
	['storageUsage', () => import('./storageUsage')],
	['scenePrivacy', () => import('./scenePrivacy')],
	['touchControls', () => import('./touchControls')],
	['playMode', () => import('./playMode')],
	['objectListNav', () => import('./objectListNav')],
	['inviteLinks', () => import('./inviteLinks')],
	['helperLayer', () => import('./helperLayer')],
	['explorerClipboard', () => import('./explorerClipboard')],
	['lookPresence', () => import('./lookPresence')],
	['postGraphs', () => import('./postGraphs')],
	['postGraphPresets', () => import('./postGraphPresets')],
	['materialSharing', () => import('./materialSharing')],
	['diagnostics', () => import('./diagnostics')],
	['wireValidate', () => import('./wireValidate')],
	['wireErrors', () => import('./wireErrors')],
	['safeStorage', () => import('./safeStorage')],
	['sceneBudget', () => import('./sceneBudget')],
	['overloadGuard', () => import('./overloadGuard')],
	['qualityGovernor', () => import('./qualityGovernor')],
	['importBudget', () => import('./importBudget')],
	['importGate', () => import('./importGate')],
	['decimate', () => import('./decimate')],
	['playCursor', () => import('./playCursor')],
	['gameStorage', () => import('./gameStorage')],
	// 30b (vr-play): the game-feel leaves under ONE name
	['gameKit', () => import('./gameKit')],
	['moduleWorld', () => import('./moduleWorld')],
	['playSpawn', () => import('./playSpawn')],
	['packRefs', () => import('./packRefs')],
	['lod', () => import('./lod')],
	['lodGroup', () => import('./lodGroup')],
	['lodGroupActions', () => import('./lodGroupActions')],
	['lodLevelEdit', () => import('./lodLevelEdit')],
	['packBehavior', () => import('./packBehavior')],
	['sceneLoader', () => import('./sceneLoader')],
	['sceneSwitch', () => import('./sceneSwitch')],
	['sceneScope', () => import('./sceneScope')],
	['kitInstancing', () => import('./kitInstancing')],
	['scriptSockets', () => import('./scriptSockets')],
	['scriptLint', () => import('./scriptLint')],
	['aiExtensions', () => import('./ai/aiExtensions')],
	['graphText', () => import('./graphText')]
];

/** hooks published at runtime through registerDebugHook @type {Record<string, any>} */
const registered = {};

/** Publish `obj` on the debug hook as `__stores[name]` — now if the hook is installed, else when
 * it is. @param {string} name @param {any} obj */
export function registerDebugHook(name, obj) {
	registered[name] = obj;
	/** @type {any} */
	const w = typeof window !== 'undefined' ? window : null;
	if (w?.__stores) w.__stores[name] = obj;
}

/** Load every row and publish `window.__stores`. @returns {Promise<Record<string, any>>} */
export function installDebugHooks() {
	return Promise.all(DEBUG_HOOKS.map(([, load]) => load())).then((mods) => {
		/** @type {Record<string, any>} */
		const stores = {};
		DEBUG_HOOKS.forEach(([name], i) => {
			if (name === '*') Object.assign(stores, mods[i]);
		});
		DEBUG_HOOKS.forEach(([name], i) => {
			if (name !== '*') stores[name] = mods[i];
		});
		Object.assign(stores, registered);
		/** @type {any} */ (window).__stores = stores;
		return stores;
	});
}
