// The flow node MANUAL: one line per node, the single source the palette tooltip, the
// editor's info pane, the docs-site reference table and the no-browser guard test all read
// (23-D4, the shaderCatalog DOCS precedent). PURE - no imports - so a node script can load it.
//
// Documentation drifts by omission: someone adds a node and nobody notices it has no
// description until a user asks what it does. tests/e2e/flow-node-docs.test.cjs asserts every
// catalog node has a line here, so a new node cannot ship undocumented.
//
// Say what the node DOES and what it is FOR, in one sentence a newcomer can act on; never
// merely restate the label.

/** @type {Record<string, string>} type -> one line */
export const NODE_DOCS = {
	slider: "An interactive slider that outputs a number - the quickest way to hand-tune any numeric input live.",
	colorpicker: "Outputs a color chosen with a swatch - the color source for anything that paints.",
	switcher: "A radio-button list that outputs the index of the selected item - a hand-operated multi-way switch.",
	number: "A constant numeric value - the simplest source node.",
	vector3: "An x/y/z triple - used as a direction, an offset, or most often a fixed point in the world.",
	toggle: "A checkbox that outputs true or false - a hand-operated on/off switch.",
	random: "A random number in a range - deterministic, so every peer sees the same \"random\" value.",
	time: "The synced clock as a value - the heartbeat behind almost every animation recipe.",
	objectselector: "Binds the graph to a scene object - the sink every effect must reach, and an object reference for sensor nodes.",
	velocity: "Outputs how fast the connected object is moving right now, in metres per second.",
	measure: "Reads a number off an object: how tall it is, where its top is, how fast it is going.",
	spawn: "Makes copies of an object while the simulation runs - crates off a conveyor, targets, debris, ammo, waves of anything.",
	flowinput: "Declares a public input socket for an object flow - the way the Scene flow feeds a value into an object's own graph.",
	flowoutput: "Declares a public output socket for an object flow - the way an object publishes a value back to the Scene flow.",
	objectflow: "Embeds an object's own graph into the Scene flow as a single card - the way to compose object flows into a bigger machine without opening each one.",
	setgamestate: "Switches the shared game state (menu, playing, paused, over) when a pulse arrives - every peer follows the same state.",
	ongamestate: "Fires a pulse when the shared game state becomes the one you pick - the hook for \"when the round starts\".",
	setcamera: "Makes a camera object the active view for every player when a pulse arrives.",
	setlook: "Points the player's view at a target when a pulse arrives - a cutscene glance or a spawn orientation.",
	gamestart: "Fires once when the game starts (Play, or a round reset) - the place to spawn, reset counters and arm timers.",
	travel: "Loads another saved scene by name when a pulse arrives - a door to the next level, replicated to everyone.",
	allplayers: "Iterates the connected players so a per-player value can be read, or a HUD row shown, for each of them.",
	setvariable: "Stores a named value in the replicated scene variables when a pulse arrives - shared state without an object.",
	getvariable: "Reads a named scene variable as a value - the read side of Set Variable, live on every peer.",
	gametime: "Seconds since the game (or the round) started, the same on every peer - a clock that pauses with the game.",
	peervariable: "A value kept PER PLAYER (score, lives, team) - each peer reads its own row, or a named player's.",
	charcontroller: "Turns the connected object into a walking, jumping character driven by the player's movement input.",
	moveinput: "The player's movement input as numbers - stick or WASD axes and the jump button - for driving things by hand.",
	possessnode: "Puts the player in control of the connected object when a pulse arrives - a vehicle, a turret, a ball.",
	camerafollow: "Makes the camera follow the connected object at a set distance and height - a third-person or chase view.",
	movespeed: "Overrides the character's walking speed while a value is wired - sprint, mud, slow motion.",
	hudscreen: "Shows or hides a whole HUD screen (a named layer of elements) while its condition holds.",
	hudbar: "Drives a HUD bar element's fill from a number - health, fuel, progress.",
	hudbutton: "Fires a pulse when a HUD button is pressed - the on-screen counterpart of On Click.",
	hudlist: "Fills a HUD list element with the items a value provides - an inventory, objectives, players.",
	hudrows: "Appends or replaces rows in a HUD rows element from a pulse - a log, a chat, a scoreboard feed.",
	hudinput: "Reads what the player typed into a HUD input element as a value.",
	hudset: "Writes a value into a HUD input element when a pulse arrives - to prefill, clear or correct it.",
	math: "Combines two numbers with an arithmetic operation.",
	compare: "Compares two numbers and outputs true or false.",
	gate: "Boolean logic on two inputs - AND, OR, NOT, XOR.",
	maprange: "Remaps a number from one range to another - the glue between free-range sources and bounded parameters.",
	select: "Chooses between two values: outputs a when the index is low, b when it's high.",
	latch: "Holds a boolean until told otherwise - set, reset and toggle pulses make it a memory bit.",
	delay: "Passes a pulse on after a set number of seconds - the timing of a fuse, or a door that closes later.",
	sequence: "Fires its outputs one after another, one per pulse, then wraps around - a step-by-step trigger.",
	once: "Lets exactly one pulse through until it is re-armed - a checkpoint, a pickup, a first-time event.",
	counter: "Counts trigger pulses and outputs the running total.",
	loop: "Sweeps a number from one value to another over time, repeating - a ready-made animation ramp.",
	timer: "A delay line: outputs its input as it was a set number of seconds ago.",
	distance: "Measures the live distance between two things in the scene.",
	proximity: "True while two things are within a radius of each other - a distance sensor with the threshold built in.",
	lookat: "Keeps the connected object facing a target - another object or a fixed point - every frame.",
	setcolor: "Paints the connected object's material with a color, re-applied every frame.",
	visibility: "Shows or hides the connected object based on a boolean.",
	setuniform: "Writes one number inside an object's shader graph, so a trigger, a",
	onclick: "Fires a short pulse when its object is clicked - the bridge from user input into the graph.",
	keypress: "Fires a pulse while a keyboard key is pressed - the bridge from your keyboard into the graph.",
	onimpact: "Fires a pulse when a physics simulation lands the connected object on the ground or another object.",
	onenter: "Fires a pulse when something enters a trigger volume - the checkpoint, doorway and pressure-plate node.",
	onexit: "Fires a pulse when something leaves a trigger volume - the other half of On Enter.",
	onrest: "Fires a pulse when a physics body has finished moving - the counterpart to On Impact, which fires when it starts.",
	gamepadbutton: "Fires a pulse (or holds a level) while a gamepad button is pressed - the pad's counterpart of Key Press.",
	gamepadaxis: "A gamepad stick or trigger axis as a number between -1 and 1, with a dead zone.",
	shake: "Jitters the connected object around its resting position - rumble, nervousness, impact feedback.",
	spin: "Rotates the connected object continuously around one axis.",
	bounce: "Bounces the connected object up and down off its resting height, like a dribbled ball.",
	orbit: "Circles the connected object around its resting position on the horizontal plane.",
	pathpatrol: "Walks the connected object along a series of waypoints you click into the scene, facing along the path.",
	animfinished: "Fires a pulse when the connected object's animation clip reaches its end.",
	animmarker: "Fires a pulse when the connected object's animation passes a named marker.",
	animstate: "Reads the connected object's animation transport as a number - playing, position or progress.",
	playanim: "Starts, stops or restarts an animation clip on the connected object when a pulse arrives.",
	mass: "Gives the connected object weight for the physics simulation - objects with a Mass fall and collide.",
	bounciness: "Sets how much the connected object rebounds in the physics simulation (restitution).",
	friction: "Sets how much the connected object grips surfaces in the physics simulation.",
	angularvelocity: "Gives the connected object a constant spin under physics - a rolling barrel, a spinning hazard, a rotating platform other objects can stand on.",
	collider: "Overrides the collision shape the physics simulation uses for the connected object - the flow equivalent of the Inspector's Physics > Collider pick, and it wins over it.",
	motor: "Drives every hinge joint attached to the connected object - the flow way to make wheels turn, turntables spin and doors swing under power.",
	impulse: "Pushes or spins a physics body when an event fires - a jump, a kick, a cannon, a nudge.",
	setvelocity: "Sets a physics body's speed outright - to launch it at an exact velocity, to hold it at a constant one, or to stop it dead.",
	joint: "Attaches two objects to each other when an event fires - a hinge, or a rigid weld.",
	pulse: "Throbs the connected object's scale in and out around its resting size.",
	blink: "Flashes the connected object on and off at a steady rate.",
	sound: "Plays an Explorer audio clip on the connected object when a pulse arrives - spatial, replicated, by content hash.",
	particle: "Emits a particle effect from the connected object - a preset burst, a stream, a trail.",
	deviceparam: "Writes a number into one parameter of the connected audio device every frame - an LFO on a cutoff, a fader on a level.",
	devicelevel: "The live output level of the connected audio device (or a wired one) as a number - a meter you can drive anything with.",
	transportbeat: "The shared music transport as a number - beat, bar, phase, bpm or playing - identical on every peer.",
	notetrigger: "Plays a note on the connected audio device when a pulse arrives - a drum pad, a sampler pad, a synth key."
};

/** the one-line manual for a node type, or '' for a type without one (a module's node) @param {string} type */
export function nodeDoc(type) {
	return NODE_DOCS[typeof type === 'string' ? type : ''] ?? '';
}
