// 38 R8 (NOTES-38 #14): the Settings rows the command palette can find, by section — generated
// from the redesign handoff inventory (cloud docs/design/redesign/screenshots/before/
// settings-inventory.json, 1.24). A pick opens Settings with the row's name in its own search, so
// the live Settings search (settingsSearch.js) decides what shows — a row renamed later still
// finds its neighbours. Regenerate when Settings gains or loses rows.

/** section title -> the `settingsSection` id that expands it (null = search only) */
export const SETTINGS_SECTION_IDS = {
	"Interface": "interface",
	"Controls": "controls",
	"Input": "input",
	"Touch controls": null,
	"Scene": "scene",
	"Explorer": "explorer",
	"VR": "vr",
	"AI": "ai",
	"Export": "export",
	"Node types": "nodetypes",
	"Connection": "connection",
	"Shortcuts": "shortcuts",
	"About": null
};

/** @type {[string, string, string][]} [section, row name, one-line description] */
export const SETTINGS_ROWS = [
	["Interface", "Allow text selection everywhere", "Off: only text fields, code, chat, logs and help text can be selected, so a drag across a menu or a panel n…"],
	["Interface", "Your character", "Pick your character, head, hat, outfit colour and ping, with a live preview on yourself."],
	["Interface", "Show everyone as classic heads", "On this device only: draws other people as the floating head instead of their animated character (lighter o…"],
	["Interface", "Theme", "UI theme for THIS device (the 3D viewport follows the environment, not the theme)"],
	["Interface", "Custom theme", "Export the active theme as an editable .theme.json, tweak the colors, then Browse to load it back"],
	["Interface", "Game sounds", "How loud a game's effects are on this device — coins, goals, hits, the clicks a game makes."],
	["Interface", "Music", "The background music a game plays while you are in Interact or Play (it stops when you go back to editing)."],
	["Interface", "Welcome on start", "Show the welcome card every time the app opens."],
	["Interface", "Announce new versions", "After an update, mark the logo menu with a dot and show one toast linking to the changelog."],
	["Interface", "Toasts in drawer only", "Hide ALL pop-up toasts in the viewport — including connection requests — so they appear only in the connect…"],
	["Interface", "Show tours automatically", "Start the short first-run tours by themselves: the editor tour after the welcome card, and \"Welcome to TheP…"],
	["Interface", "VR welcome", "Your controllers, moving, pointing, grabbing, the radial menu, playing and leaving VR."],
	["Interface", "Editor tour", "Six steps around the editor — adding things, looking around, the tools, Play, building together and the log…"],
	["Interface", "Offer Enter VR", "In a headset's browser (Quest), let the browser show its own \"Enter VR\" button for this page, once per visit."],
	["Interface", "Reset tours", "Forget which tours you have seen or skipped and turn automatic tours back on"],
	["Interface", "Floating toolbar", "The bottom toolbar lifts above the docked Node editor or Explorer when one opens, so it never sits over the…"],
	["Interface", "Toolbar always on top", "The bottom toolbar paints over the docked panels and over floating windows, so it is always reachable."],
	["Interface", "Window positions", "Bring back any floating window (object list, chat, Explorer, editors) that drifted off-screen or behind the UI"],
	["Interface", "Touch tools", "Undo / Redo / Multi-select buttons beside the logo, for touch — no Ctrl+Z or Shift needed."],
	["Interface", "Allow undocking (touch)", "On touch / small screens the Flow and Explorer panels stay docked and their \"undock\" buttons are hidden (fl…"],
	["Interface", "Advanced mode", "Show system objects (module content, environment rig) as a System filter in the object list"],
	["Interface", "Environment in list", "Show the environment group as an Environment filter in the object list"],
	["Interface", "Object search in menu", "Add a \"Search objects…\" entry to the viewport right-click menu — find a scene object and fly the camera to it"],
	["Interface", "Show FPS + draw calls", "A small counter with the frame rate, frame time, draw calls and triangles — in the corner of the viewport a…"],
	["Interface", "Dock resizes the viewport", "On, the 3D view ends where an open bottom panel begins — the way every editor lays out its viewport, so not…"],
	["Controls", "Shift+A quick add", "Pressing Shift+A opens the Add menu at the cursor and spawns the picked object under it."],
	["Controls", "Show helpers in Play (debug)", "Light helpers, camera frustums and camera markers hide when Play starts (camera previews and captures never…"],
	["Controls", "Double-click to open notes", "A single click on a note marker — and the notes drawer's ‹ › group arrows — then only flies the camera to t…"],
	["Controls", "Trackpad gestures", "Two-finger swipes on a laptop trackpad pan the camera; pinch zooms."],
	["Controls", "Two-finger pan", "Two-finger swipes pan the camera."],
	["Controls", "Reverse trackpad pan", "Flip the two-finger pan direction (default: the scene follows your fingers, like touch scrolling)"],
	["Controls", "Pinch zoom", "Pinching in/out on the viewport zooms the camera."],
	["Controls", "Allow browser pinch zoom", "Accessibility: let pinch / Ctrl+scroll zoom the whole PAGE again (off keeps pinch as an app gesture and sto…"],
	["Controls", "Wheel diagnostics", "Linux · Chromium · pointer: fine · wheel mode: auto\n\nScroll over the viewport — the last 8 wheel events lan…"],
	["Input", "Gamepad", "A connected controller drives the game with no setup: the left stick walks, the right stick looks, and the…"],
	["Input", "Swap sticks", "Move with the RIGHT stick and look with the left — the southpaw layout"],
	["Input", "Invert look Y", "Push the look stick up to look DOWN (the flight-stick convention)"],
	["Input", "Stick deadzone", "How far a stick may drift at rest before it counts as pushed (0.05–0.4)."],
	["Input", "Look sensitivity", "How fast the look stick turns (0.5–3×)."],
	["Input", "Per-game controls", "A scene can bind the pad itself with the Gamepad Button and Gamepad Axis nodes in the node editor (Input gr…"],
	["Input", "Mouse bindings", "Classic (the default): a left drag on the node editor's canvas pans and Shift+drag draws a selection box."],
	["Touch controls", "Show touch controls", "Auto shows the stick and action buttons in Play on a touch screen (or once you touch the screen)."],
	["Touch controls", "Show in edit", "Also draw the action buttons while editing (they press keys there too)."],
	["Touch controls", "Haptic tick", "A short vibration when a button is pressed (phones that support it)"],
	["Touch controls", "Look speed", "How far a drag on the right half turns the view (1.00×)"],
	["Touch controls", "Layout", "Drag, resize and fade the stick and every button — for this game or all games, saved on this device."],
	["Touch controls", "Jump", "Released\nUpload\nExplorer…\nPressed\nUpload\nExplorer…\nTint\nSize"],
	["Touch controls", "Fire", "Released\nUpload\nExplorer…\nPressed\nUpload\nExplorer…\nTint\nSize"],
	["Touch controls", "Use", "Released\nUpload\nExplorer…\nPressed\nUpload\nExplorer…\nTint\nSize"],
	["Touch controls", "Grab", "Released\nUpload\nExplorer…\nPressed\nUpload\nExplorer…\nTint\nSize"],
	["Touch controls", "Crouch", "Released\nUpload\nExplorer…\nPressed\nUpload\nExplorer…\nTint\nSize"],
	["Touch controls", "Sprint", "Released\nUpload\nExplorer…\nPressed\nUpload\nExplorer…\nTint\nSize"],
	["Touch controls", "Reload", "Released\nUpload\nExplorer…\nPressed\nUpload\nExplorer…\nTint\nSize"],
	["Touch controls", "Up", "Released\nUpload\nExplorer…\nPressed\nUpload\nExplorer…\nTint\nSize"],
	["Touch controls", "Down", "Released\nUpload\nExplorer…\nPressed\nUpload\nExplorer…\nTint\nSize"],
	["Scene", "Show grid", "Display grid on floor"],
	["Scene", "Light helper length", "How far a directional or spot light's helper line reaches along its direction (display only — a directional…"],
	["Scene", "Shadow quality", "Caps every light's shadow map size on THIS machine (Off disables shadows entirely; per-light sizes still re…"],
	["Scene", "Reduce quality when the scene is heavy", "When a heavy scene cannot keep 30 frames a second on THIS machine, drop shadows, then resolution, then effe…"],
	["Scene", "Simplify distant models", "Draw a lighter version of a dense model (a few thousand triangles or more) when it is far from you, built o…"],
	["Scene", "Draw repeated kit pieces together", "Every copy of one pack piece (a wall, a floor tile, a battlement) is drawn in one go instead of one by one,…"],
	["Scene", "Placement preview", "What an item dragged in from the Explorer shows before you drop it: the full model, the model within a triangle budget, or its box"],
	["Scene", "Preview triangle budget", "Above this a loaded model previews as its box while you drag it in (50k on a desktop, 15k on a phone or headset)"],
	["Scene", "Show dimensions", "Width × depth × height in metres, and the triangles and download size, beside the pointer while you drag an item in"],
	["Scene", "Water quality", "High draws refraction, caustics, shoreline foam and planar mirrors at full resolution; Medium at half; Low…"],
	["Scene", "Simulation controls", "Show the physics transport (play/pause/stop/reset) at bottom-right."],
	["Scene", "Sync animations", "Node animations use wall-clock time so all peers see the same phase"],
	["Scene", "Spatial voice", "Voices come from where each peer is (pan + distance falloff)"],
	["Scene", "Ping color + sound", "Your ping color + sound — peers see and hear YOUR pings this way (color empty = your peer color)"],
	["Scene", "Autosave", "Keep a local session snapshot (restore offered after a crash/reload)"],
	["Scene", "Auto-restore on load", "Restore that snapshot automatically at startup instead of asking."],
	["Scene", "Keep automatic checkpoints", "While you work, autosave also adds a row to the checkpoint timeline every few minutes — only when the scene…"],
	["Scene", "Automatic checkpoint every", "The shortest gap between two automatic checkpoints"],
	["Scene", "Checkpoint storage", "How much of this device checkpoints may use."],
	["Scene", "When opening another scene", "Modules that came with the scene you are leaving (a game's Waves or Untangle) and that the next scene does…"],
	["Scene", "Double-click action", "What a double-click on an object does in the viewport."],
	["Scene", "Length", "How distances are shown and typed — positions, snapping steps, bevel widths."],
	["Scene", "Angle", "The same for rotations and angular snapping."],
	["Scene", "Carry animation clips", "A duplicate gets its own copy of the object's animation clips, so the copy plays independently."],
	["Scene", "Carry object flow", "A duplicate gets its own copy of the object's flow graph, with fresh node ids."],
	["Scene", "Carry shader graph", "A duplicate of a shader-driven object gets its own copy of the graph."],
	["Scene", "Share materials", "Off (the default), a duplicate gets its own copy of the material, so editing one leaves the other alone."],
	["Scene", "Wireframe color", "Line color of the Wireframe view mode (Configure Scene ▸ View mode)"],
	["Scene", "Selection outline color", "Outline drawn around your selected objects (objects a peer has locked keep their own color)"],
	["Scene", "Edit Mesh wireframe", "Edge overlay while editing a mesh."],
	["Scene", "Reset line colors", "Back to the defaults (#9aa4b0 / #353535 / auto)."],
	["Scene", "Loading placeholders", "What a kit piece shows while its file is still loading."],
	["Scene", "Placeholder grid texture", "A prototype grid on the modern boxes, sized in world metres so every box reads at the same scale"],
	["Scene", "Grid size (m)", "One grid cell, in metres (default 0.5)"],
	["Scene", "Grid color", "The grid lines' colour"],
	["Scene", "Grid opacity", "How strongly the grid shows on the boxes"],
	["Scene", "Placeholder animation speed", "The pulse and the scan sweep of the modern boxes (0 = still)"],
	["Scene", "Stuck after (seconds)", "A loading piece with no new data for this long turns amber; three times this long and the download is resta…"],
	["Explorer", "When you add files during a session", "A file is local until somebody says otherwise, so this is what happens when you add one while connected."],
	["Explorer", "Download shared files automatically", "When somebody shares a file or a folder, fetch it straight away."],
	["Explorer", "Offer to merge unsaved work on connect", "When you connect with work in a scene that was never saved, this app asks you to save it or dismiss it — an…"],
	["Explorer", "Who can unshare a file", "A shared file is part of the project, so by default any editor can take it out again — the same way anyone…"],
	["Explorer", "Keep versions per scene", "How many past versions of each scene keep their bytes on this machine — browse them under Version history i…"],
	["Explorer", "When importing files already in your library", "Rule for importing same files which already in your library."],
	["Explorer", "Save name", "What a downloaded scene, project or GLTF file is called."],
	["Explorer", "Keep a recycle bin", "Deleting a shared file removes it from the project for everyone, so each peer keeps its own copy in Deleted…"],
	["Explorer", "Delete without asking", "Skip the confirmation when deleting files and folders."],
	["Explorer", "Keep deleted files after a reload", "Off by default: the bin is a safety net for the minutes after a delete, not storage, so its files are recla…"],
	["Explorer", "Deleted files log", "Keep a record of what was deleted from this project — the name, who removed it, when, and the thumbnail tak…"],
	["Explorer", "Storage used", "What is using this device’s storage — your library files, saved scenes and projects, old scene versions, th…"],
	["VR", "VR override", "Forces normal play even if immersive-vr is enabled"],
	["VR", "Turning", "· now Snap"],
	["VR", "Snap angle", "· now 45°"],
	["VR", "Smooth speed", "· now 90°/s"],
	["VR", "Mirror turn", ""],
	["VR", "Comfort vignette", "Darkens the edges while the stick moves or turns you"],
	["VR", "Teleport", "Push the teleport stick up to aim, let go to land"],
	["VR", "Flying", "In Edit the move stick follows where that controller points"],
	["VR", "Stance", "Seated lifts your view to a standing eye height· now Standing"],
	["VR", "Height", "· now 0 cm"],
	["VR", "Menu hand", "Which controller opens the radial menu; the other one points· now Right"],
	["VR", "Hold to open menu", "Hold the menu button, release over a sector to pick it"],
	["VR", "Left-handed", "Mirrors every button to the other hand"],
	["VR", "Grab style", "Rigid: the controller is the handle (the stick reels and scales)· now Rigid"],
	["VR", "Refresh rate", "120 Hz needs the headset’s own 120 Hz setting· now Max"],
	["VR", "Statistics card", "A card on the other hand: peers, objects, network"],
	["VR", "Peer hands", "How hand-tracked peers look to you· now Hands"],
	["VR", "Passthrough", "Mixed reality — applies on the next VR entry— not supported on this device"],
	["VR", "Selection wireframe", "Draws a wireframe over what you select"],
	["VR", "Reset panel positions", "Panels you moved go back to their spots on the controllers"],
	["VR", "Game HUD", "Where a game’s score and timer show in the headset· now Follow head"],
	["VR", "Game HUD size", "· now Medium"],
	["VR", "Button hints", "Shows which button jumps, fires or opens the menu in a game"],
	["VR", "Hold to move vertex", "Off: press to pick a vertex up, press again to drop it"],
	["VR", "Sleeve palette", "Experimental: drag shapes off a strip on your forearm"],
	["VR", "Face edit limit", "· now 2500 tris"],
	["VR", "Vertex edit limit", "· now 800 verts"],
	["VR", "My hand model", "Custom hands (identity) — a GLB from your Explorer library that OTHER peers see as your hands in VR (bytes…"],
	["VR", "Colocation probe (dev)", "CO0 on-device probe — run this inside the headset: it opens an immersive-ar session, creates an anchor at y…"],
	["VR", "Colocation", "Not colocated — share one physical room with a co-present peer."],
	["VR", "Ghost hands", "While colocated, a room-mate's avatar body, name label and voice are hidden — you are looking at and listen…"],
	["AI", "Enable assistant", "AI scene assistant — build and edit the scene with prompts."],
	["AI", "Providers", "No providers yet."],
	["AI", "Voice typing provider", "Speech to text for the assistant's mic — in the AI window and in VR (Tools ▸ AI: hold the mic or the talk b…"],
	["AI", "Voice typing server", "Test connection"],
	["AI", "Mesh generation", "Text → 3D mesh — generate custom models from prompts (Add menu → “✨ Generate 3D model”, or the assistant)."],
	["AI", "Mesh providers", "No mesh providers yet."],
	["AI", "Storage", "API keys are stored unencrypted in this browser's local storage (like all settings) and never leave your de…"],
	["Export", "Show Made with ThePrototype badge", "Always on in play links, embeds and exported games: a small logo in the bottom-right corner that opens thep…"],
	["Export", "Start fullscreen", "The first Play press also asks the browser for fullscreen (a page may only go fullscreen on a click)."],
	["Export", "Show FPS", "The game starts with its frame counter on."],
	["Export", "Quality", "The quality a player starts at."],
	["Export", "Include VR button", "On a headset browser the start card offers Enter VR."],
	["Export", "Use CDN for packs", "Smaller zip: kit pieces load from the packs CDN when the game starts, so it needs internet."],
	["Export", "Compress textures", "Not in this release: textures go into the export exactly as authored."],
	["Connection", "Session size", "How many people you expect in a session."],
	["Connection", "Signaling server", "Where peers discover each other."],
	["Connection", "Apply changes", "Switches the signaling server now and keeps your session id; an open session is left first."],
	["About", "Version", "1.24.0-dev (84492c3)"],
	["About", "Diagnostics", "What the app has been doing: version, this session's peer and scene counts, and the last 300 log lines."],
	["About", "Dev Builds", "https://alexz005.github.io/theprototype"],
	["About", "Source Code", "github.com/theprototype-app/core"],
	["About", "Modules", "github.com/theprototype-app/modules"],
	["About", "Docs", "github.com/theprototype-app/docs"],
];
