<script>
	// 38 R10 — THE icon component (SPEC §7). Every icon under src/components goes through
	// here: static markup (`<Icon name="play" />`) and data-driven names alike (Explorer kind
	// icons, menu item defs, a toolbar's tool table). One map means a glyph is swapped in ONE
	// place, which is how the custom domain set lands (cloud docs/design/redesign/icons-brief.md).
	// Names are lucide kebab-case. Sizes snap to 16/20 (UI) or 24/32/48 (placeholder art) and
	// the stroke is one standard — both in $lib/ui/icons.js. tests/unit/iconLint.test.js keeps
	// components off '@lucide/svelte' and checks every literal name below exists.
	import {
		Activity,
		AlignCenterHorizontal,
		AlignCenterVertical,
		AlignEndHorizontal,
		AlignEndVertical,
		AlignHorizontalSpaceAround,
		AlignStartHorizontal,
		AlignStartVertical,
		AlignVerticalSpaceAround,
		AppWindow,
		Archive,
		ArrowDownToLine,
		ArrowRight,
		AudioLines,
		Bell,
		BookOpen,
		Bookmark,
		Box,
		BoxSelect,
		Boxes,
		Braces,
		Brush,
		Bug,
		Camera,
		CaseSensitive,
		Check,
		ChevronDown,
		ChevronLeft,
		ChevronRight,
		ChevronUp,
		ChevronsLeftRight,
		Circle,
		CircleAlert,
		CircleCheck,
		CircleDashed,
		CircleHelp,
		Clapperboard,
		ClipboardCopy,
		ClipboardPaste,
		Code,
		Cog,
		Columns2,
		Columns3,
		Combine,
		Compass,
		Copy,
		CornerLeftUp,
		Crosshair,
		Download,
		Droplet,
		Droplets,
		Ellipsis,
		ExternalLink,
		Eye,
		EyeOff,
		FileCode,
		FileInput,
		FilePlus,
		FileText,
		Filter,
		Flag,
		FlipHorizontal,
		FlipVertical,
		Focus,
		Folder,
		FolderDown,
		FolderInput,
		FolderOpen,
		FolderPlus,
		FolderTree,
		Gamepad2,
		Gauge,
		Ghost,
		Gift,
		GitBranchPlus,
		GitCompare,
		Glasses,
		Globe,
		Grid2x2,
		Grid3x3,
		GripVertical,
		Group,
		Hand,
		HardDrive,
		Heart,
		History,
		House,
		Image,
		ImagePlus,
		Import,
		Inbox,
		Info,
		Keyboard,
		Lasso,
		Layers,
		LayoutDashboard,
		LayoutGrid,
		LayoutTemplate,
		Link,
		Link2,
		List,
		ListTree,
		LoaderCircle,
		LocateFixed,
		Lock,
		Magnet,
		Map as MapIcon,
		Maximize2,
		Menu,
		MessageSquare,
		Mic,
		MicOff,
		Minus,
		Monitor,
		Mountain,
		MousePointer2,
		Move,
		Move3d,
		Music,
		Network,
		Package,
		PackageOpen,
		Palette,
		PanelBottom,
		PanelLeft,
		PanelRight,
		Pause,
		PenTool,
		Pencil,
		PersonStanding,
		Pin,
		PinOff,
		Pipette,
		Play,
		Plus,
		Proportions,
		Puzzle,
		Radar,
		RectangleGoggles,
		Redo2,
		RefreshCw,
		Regex,
		Repeat,
		Rewind,
		RotateCcw,
		RotateCw,
		Save,
		Scissors,
		ScrollText,
		Search,
		Settings,
		Settings2,
		Share2,
		Shrink,
		SkipBack,
		SkipForward,
		SlidersHorizontal,
		Sparkles,
		Spline,
		Square,
		SquareDashed,
		SquareMousePointer,
		SquarePen,
		Star,
		StepBack,
		StepForward,
		StickyNote,
		Sun,
		Target,
		TextQuote,
		Timer,
		ToggleLeft,
		Trash2,
		Type,
		Undo2,
		Ungroup,
		Unlink,
		Upload,
		UserLock,
		UserPlus,
		UserRound,
		Users,
		Video,
		VideoOff,
		Volume2,
		VolumeX,
		WandSparkles,
		Waypoints,
		WholeWord,
		Workflow,
		Wrench,
		X,
		Zap,
		ZoomIn,
		ZoomOut
	} from '@lucide/svelte';
	import ToolIcon from './ToolIcon.svelte';
	import { iconSize, ICON_STROKE } from '$lib/ui/icons.js';

	// W8b: `MAP[name] ?? Box` means an unmapped name renders a SQUARE, silently — which is what
	// the toolbar's reorder controls had been drawing since they shipped, two identical boxes
	// where a direction was meant to be. Any name a menu passes has to exist here (a literal one
	// is checked by the lint test; a dev build warns about the rest).
	/** @type {Record<string, any>} */
	const MAP = {
		activity: Activity,
		'align-center-horizontal': AlignCenterHorizontal,
		'align-center-vertical': AlignCenterVertical,
		'align-end-horizontal': AlignEndHorizontal,
		'align-end-vertical': AlignEndVertical,
		'align-horizontal-space-around': AlignHorizontalSpaceAround,
		'align-start-horizontal': AlignStartHorizontal,
		'align-start-vertical': AlignStartVertical,
		'align-vertical-space-around': AlignVerticalSpaceAround,
		'app-window': AppWindow,
		archive: Archive,
		'arrow-down-to-line': ArrowDownToLine,
		'arrow-right': ArrowRight,
		'audio-lines': AudioLines,
		bell: Bell,
		'book-open': BookOpen,
		bookmark: Bookmark,
		box: Box,
		'box-select': BoxSelect,
		boxes: Boxes,
		braces: Braces,
		brush: Brush,
		bug: Bug,
		camera: Camera,
		'case-sensitive': CaseSensitive,
		check: Check,
		'chevron-down': ChevronDown,
		'chevron-left': ChevronLeft,
		'chevron-right': ChevronRight,
		'chevron-up': ChevronUp,
		'chevrons-left-right': ChevronsLeftRight,
		circle: Circle,
		'circle-alert': CircleAlert,
		'circle-check': CircleCheck,
		'circle-dashed': CircleDashed,
		'circle-help': CircleHelp,
		clapperboard: Clapperboard,
		'clipboard-copy': ClipboardCopy,
		'clipboard-paste': ClipboardPaste,
		code: Code,
		cog: Cog,
		'columns-2': Columns2,
		'columns-3': Columns3,
		combine: Combine,
		compass: Compass,
		copy: Copy,
		'corner-left-up': CornerLeftUp,
		crosshair: Crosshair,
		download: Download,
		droplet: Droplet,
		droplets: Droplets,
		ellipsis: Ellipsis,
		'external-link': ExternalLink,
		eye: Eye,
		'eye-off': EyeOff,
		'file-code': FileCode,
		'file-input': FileInput,
		'file-plus': FilePlus,
		'file-text': FileText,
		filter: Filter,
		flag: Flag,
		'flip-horizontal': FlipHorizontal,
		'flip-vertical': FlipVertical,
		focus: Focus,
		folder: Folder,
		'folder-down': FolderDown,
		'folder-input': FolderInput,
		'folder-open': FolderOpen,
		'folder-plus': FolderPlus,
		'folder-tree': FolderTree,
		'gamepad-2': Gamepad2,
		gauge: Gauge,
		ghost: Ghost,
		gift: Gift,
		'git-branch-plus': GitBranchPlus,
		'git-compare': GitCompare,
		glasses: Glasses,
		globe: Globe,
		'grid-2x2': Grid2x2,
		'grid-3x3': Grid3x3,
		'grip-vertical': GripVertical,
		group: Group,
		hand: Hand,
		'hard-drive': HardDrive,
		heart: Heart,
		history: History,
		house: House,
		image: Image,
		'image-plus': ImagePlus,
		import: Import,
		inbox: Inbox,
		info: Info,
		keyboard: Keyboard,
		lasso: Lasso,
		layers: Layers,
		'layout-dashboard': LayoutDashboard,
		'layout-grid': LayoutGrid,
		'layout-template': LayoutTemplate,
		link: Link,
		'link-2': Link2,
		list: List,
		'list-tree': ListTree,
		'loader-circle': LoaderCircle,
		'locate-fixed': LocateFixed,
		lock: Lock,
		magnet: Magnet,
		map: MapIcon,
		'maximize-2': Maximize2,
		menu: Menu,
		'message-square': MessageSquare,
		mic: Mic,
		'mic-off': MicOff,
		minus: Minus,
		monitor: Monitor,
		mountain: Mountain,
		'mouse-pointer-2': MousePointer2,
		move: Move,
		'move-3d': Move3d,
		music: Music,
		network: Network,
		package: Package,
		'package-open': PackageOpen,
		palette: Palette,
		'panel-bottom': PanelBottom,
		'panel-left': PanelLeft,
		'panel-right': PanelRight,
		pause: Pause,
		'pen-tool': PenTool,
		pencil: Pencil,
		'person-standing': PersonStanding,
		pin: Pin,
		'pin-off': PinOff,
		pipette: Pipette,
		play: Play,
		plus: Plus,
		proportions: Proportions,
		puzzle: Puzzle,
		radar: Radar,
		'rectangle-goggles': RectangleGoggles,
		'redo-2': Redo2,
		'refresh-cw': RefreshCw,
		regex: Regex,
		repeat: Repeat,
		rewind: Rewind,
		'rotate-ccw': RotateCcw,
		'rotate-cw': RotateCw,
		save: Save,
		scissors: Scissors,
		'scroll-text': ScrollText,
		search: Search,
		settings: Settings,
		'settings-2': Settings2,
		'share-2': Share2,
		shrink: Shrink,
		'skip-back': SkipBack,
		'skip-forward': SkipForward,
		'sliders-horizontal': SlidersHorizontal,
		sparkles: Sparkles,
		spline: Spline,
		square: Square,
		'square-dashed': SquareDashed,
		'square-mouse-pointer': SquareMousePointer,
		'square-pen': SquarePen,
		star: Star,
		'step-back': StepBack,
		'step-forward': StepForward,
		'sticky-note': StickyNote,
		sun: Sun,
		target: Target,
		'text-quote': TextQuote,
		timer: Timer,
		'toggle-left': ToggleLeft,
		'trash-2': Trash2,
		type: Type,
		'undo-2': Undo2,
		ungroup: Ungroup,
		unlink: Unlink,
		upload: Upload,
		'user-lock': UserLock,
		'user-plus': UserPlus,
		'user-round': UserRound,
		users: Users,
		video: Video,
		'video-off': VideoOff,
		'volume-2': Volume2,
		'volume-x': VolumeX,
		'wand-sparkles': WandSparkles,
		waypoints: Waypoints,
		'whole-word': WholeWord,
		workflow: Workflow,
		wrench: Wrench,
		x: X,
		zap: Zap,
		'zoom-in': ZoomIn,
		'zoom-out': ZoomOut
	};

	// `snap={false}` keeps a size as given. Only for glyphs that are not UI icons: authored game
	// HUD content (HudElement) and a tick drawn INSIDE a 16px control (Checkbox). The lint test
	// holds that list.
	/** @type {{ name: string, size?: number, strokeWidth?: number, snap?: boolean } & Record<string, any>} */
	let { name, size = 16, strokeWidth = ICON_STROKE, snap = true, ...rest } = $props();
	// `tool:<name>` is the custom domain set (ToolIcon.svelte's duotone glyphs, lucide's grid)
	const tool = $derived(String(name).startsWith('tool:') ? String(name).slice(5) : null);
	const Cmp = $derived(MAP[name] ?? Box);
	const px = $derived(snap ? iconSize(size) : size);

	$effect(() => {
		if (import.meta.env.DEV && !tool && !(name in MAP)) console.warn(`Icon: no icon named "${name}" in ui/Icon.svelte's map`);
	});
</script>

{#if tool}
	<ToolIcon name={tool} size={px} {strokeWidth} class={rest.class} />
{:else}
	<Cmp size={px} {strokeWidth} aria-hidden="true" {...rest} />
{/if}
